# Generated by Django 4.2.16 on 2024-10-03 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='comment',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rate',
            field=models.PositiveSmallIntegerField(choices=[(1, 'سيء جداً'), (2, 'سيء'), (3, 'جيد'), (4, 'جيد جداً'), (5, 'ممتاز')]),
        ),
    ]
