# Generated by Django 4.2.16 on 2024-10-09 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_product_pickup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pickup',
        ),
    ]
