# Generated by Django 4.2.16 on 2024-10-09 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('car_order', 'طلب سيارة'), ('pickup_order', 'طلب مسبق'), ('home_order', 'طلب بيت')], max_length=20, null=True),
        ),
    ]
