# Generated by Django 4.2.16 on 2024-10-09 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_order_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_type',
        ),
    ]
