# Generated by Django 4.2.14 on 2024-10-11 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_order_is_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='unknown_user',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
